services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: internship
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/data/postgres

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db

  rabbitmq: 
    image: rabbitmq:3-management-alpine 
    ports: 
      - 5672:5672 
      - 15672:15672 
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq 
      - rabbitmq_log:/var/log/rabbitmq

  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #     - redis
  #   ports:
  #     - "8080:8080"
  #     - "8090:8090"

volumes:
  mongo-db:
  postgres-db:
  redis-data:
  rabbitmq_data:
  rabbitmq_log:
